### ISSUE TITLE
1.5.x

### ISSUE THREAD

**Issue by splitice** [HoopCHINA/ngx_http_redis#1]
Needs upgrade to support the upstream API changes.

Results in issues like - 
2013/11/28 01:53:33 [error] 25107#0: *421 srcache_fetch: cache sent truncated status line or headers while sending to client, client: 108.162.219.227, server: www.highway.cf, request: "GET /shop/img/chat.png HTTP/1.1", subrequest: "/__redis_read", upstream: "redis://X:6380",

and occasionally

2013/11/28 01:54:48 [error] 25107#0: *1127 redis sent invalid trailer while sending to client, client: 14.203.10.166, server: , request: "GET /images/logo.png HTTP/1.1", subrequest: "/__redis_read", upstream: "redis://X:6380", host:

Seems to be to do with the parsing of the response (in the filter).

**Comment by soplwang** [comment]
Ok, I'll check on it

**Comment by splitice** [comment]
Thank you, I hope to see it :)

agentzh and myself were both working on patches for support.

This will be great since I will be able to see if I was on the right track with my changes (I am only a fairly new nginx developer).

And thank you for your time, you do great work :+1:

**Comment by splitice** [comment]
FYI from what I understand u->length has changed, and u->headers_in.content_length_n is mostly the same. I have a committed version using that, I am not sure if it works in all situations yet.

**Comment by soplwang** [comment]
@splitice I'm not original author, but like you that fork the origin module and improved for our site's use case.

I've reviewed your improves and think you've done this issue! Great!

**Comment by splitice** [comment]
Oh well, I found the module through you :p

FYI Maxim made a one line patch for the issue which fixed it perfectly. :) Its in nginx-dev

```
--- ngx_http_redis_module.c.orig        2013-11-28 13:35:28.000000000 +0400
+++ ngx_http_redis_module.c     2013-11-28 13:37:19.000000000 +0400
@@ -578,7 +578,7 @@ ngx_http_redis_filter_init(void *data)

     u = ctx->request->upstream;

-    u->length += NGX_HTTP_REDIS_END;
+    u->headers_in.content_length_n + NGX_HTTP_REDIS_END;

     return NGX_OK;
 }
```

Much nicer than my first solution :)

**Comment by soplwang** [comment]
Got, thank you! :+1:
