### ISSUE TITLE
您好

### ISSUE THREAD

**Issue by lidaohang** [HoopCHINA/ngx_http_redis#2]
您好，章老师，ngx_http_redis_process_header
upstream 读后端redis的数据，怎么才知道读完了没？ 以前http 是一个hander的长度，根据这个长度，来对比知道读了多少~ 但是redis协议里面没有这样的~
如果遇到大value， 我怎么判断才能把value读完，然后解析解析处理包装~

**Comment by soplwang** [comment]
redis 协议有长度字段的。

发自我的 iPhone

**Comment by lidaohang** [comment]
我看您的这个，貌似没有处理的吧~

**Comment by lidaohang** [comment]
我开发的upstream redis模块。 ab压力测试好多499， 
这个咋解决，我已经把   proxy_ignore_client_abort on; 开启了。

**Comment by soplwang** [comment]
@lidaohang Pls see:
ngx_http_redis_module.c#L522

**Comment by soplwang** [comment]
Maybe https://github.com/splitice/ngx_http_redis fork more suitable for you.

**Comment by lidaohang** [comment]
感谢您的回复，我大致压测了下nginx，单核 后端一个redis实例  
ab 压测只能到3w左右， nginx单个work的cpu接近90%
redis可以到4w的qps，为啥ngx_redis_upstream只能到3w左右？
